// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 202601010000_users.sql

package db

import (
	"context"
)

const delUser = `-- name: DelUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DelUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, delUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const setUser = `-- name: SetUser :exec
INSERT INTO users (id, created_at) VALUES ($1, $2)
`

type SetUserParams struct {
	ID        string
	CreatedAt int64
}

func (q *Queries) SetUser(ctx context.Context, arg SetUserParams) error {
	_, err := q.db.Exec(ctx, setUser, arg.ID, arg.CreatedAt)
	return err
}
